@rootUrl = http://localhost:8000

### check server
GET {{rootUrl}}




### new user### new user
POST {{rootUrl}}/api/v1/user/new
Content-Type: application/json

{
  "_id": "user_2",
  "name": "Shankar Pandey2",
  "email": "shankar2@example.com",
  "photo": "https://example.com/profile.jpg",
  "gender": "male",
  "dob": "1998-05-12"
}
  

### get all users

GET {{rootUrl}}/api/v1/user/all



### get user by ID

GET {{rootUrl}}/api/v1/user/user_1



### delete User

DELETE  {{rootUrl}}/api/v1/user/user_1